<x-admin.base>
  <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed, dicta?</p>
  <p>Alias voluptate officia possimus labore vero, beatae debitis. Fugiat, commodi?</p>
  <p>Porro laudantium voluptates laboriosam dignissimos a repudiandae qui necessitatibus similique.</p>
  <p>Dolores molestiae nam ipsum asperiores! Doloribus natus iste incidunt harum.</p>
  <p>Sequi possimus commodi maxime assumenda odit, fuga expedita iste sed?</p>
  <p>Voluptatibus odio sint quisquam ad quidem. Perferendis ratione nemo natus!</p>
  <p>Deserunt labore odit ipsum harum veniam veritatis minus similique culpa?</p>
  <p>Qui nihil at corrupti ea doloribus! Voluptatum nemo adipisci labore.</p>
  <p>Minima, itaque vero. Corporis sit, eum exercitationem ex quae beatae?</p>
  <p>Accusamus veritatis laborum, harum unde voluptatum dolorum minus aspernatur soluta!</p>
  <p>Vero dolorem nulla obcaecati natus expedita, repellendus quasi esse maiores?</p>
  <p>Voluptatum iure odit ut neque placeat possimus aut commodi sint?</p>
  <p>Nihil maiores quo sed architecto aperiam nobis consequuntur voluptates! Voluptatem.</p>
  <p>Odio aut laborum consequuntur culpa quam nesciunt ipsa repellendus quis!</p>
  <p>Quos tempora asperiores illo doloremque excepturi amet consequuntur quam blanditiis.</p>
  <p>Odit, magni maxime. Repudiandae corrupti deleniti laborum explicabo excepturi pariatur.</p>
  <p>Veniam autem illo officia assumenda at saepe maxime sequi ex?</p>
  <p>Quasi quaerat est molestiae officiis tempore itaque minima laudantium fugiat.</p>
  <p>Placeat alias odit fugit tenetur ratione? Reiciendis quaerat ducimus nam.</p>
  <p>Nisi voluptas aliquid cupiditate minus totam consectetur fugit, molestiae at!</p>
  <p>Nesciunt rerum consectetur deleniti sit temporibus! Numquam molestiae eaque maxime.</p>
  <p>In quidem laboriosam dolorum magnam temporibus dolore facere, dolores similique!</p>
  <p>Laborum cupiditate distinctio beatae officia quibusdam quo, ipsum pariatur rem.</p>
  <p>Accusantium reprehenderit quis aliquid dicta eaque laborum exercitationem porro enim!</p>
  <p>Nisi ipsam doloremque velit tempora quasi illo obcaecati officiis ipsa?</p>
  <p>Neque cumque iusto nemo at, laborum unde rerum! Quas, placeat.</p>
  <p>Quas, excepturi ad. Maiores porro quia quam aspernatur autem recusandae!</p>
  <p>Error aliquam neque impedit sed aperiam magnam fuga vitae vel!</p>
  <p>Nulla praesentium quam natus commodi reprehenderit libero accusantium ea culpa!</p>
  <p>Explicabo laborum sapiente velit ipsam consequatur blanditiis magnam culpa atque!</p>
  <p>Voluptates reprehenderit doloribus corporis architecto esse itaque perferendis animi ipsa?</p>
  <p>Ullam consectetur aliquid nesciunt et earum praesentium veritatis animi tempore!</p>
  <p>Necessitatibus vel modi odio architecto nulla aliquam autem dolore nihil.</p>
  <p>Rerum, necessitatibus sunt velit voluptatibus asperiores itaque fugit blanditiis dolore.</p>
  <p>Distinctio deleniti sint sapiente facilis omnis sequi qui amet error?</p>
  <p>Ipsum, tempora sequi atque optio deserunt excepturi inventore quod modi.</p>
  <p>Labore animi possimus quam error inventore dolor numquam, earum nam!</p>
  <p>Facilis, eos tempora? Architecto deleniti quaerat, aspernatur possimus delectus repellendus.</p>
  <p>Accusamus unde impedit fuga debitis suscipit voluptatem dolore error delectus.</p>
  <p>Aperiam, distinctio architecto similique expedita nulla quidem maxime dignissimos natus!</p>
  <p>Deserunt nostrum ullam rem ea sapiente, labore pariatur beatae optio.</p>
  <p>Ea accusamus quas nulla libero odio accusantium quidem ipsum perferendis!</p>
  <p>Assumenda eum voluptas ipsa dolorum in inventore nostrum cupiditate explicabo.</p>
  <p>Aut eos, officiis itaque quod provident quisquam perspiciatis quaerat fuga?</p>
  <p>Facilis quaerat, in natus ipsum magnam quidem eum sunt incidunt.</p>
  <p>Aperiam quibusdam hic magni cupiditate itaque cumque laudantium iste ut!</p>
  <p>Nulla, facere unde assumenda tempore aliquid expedita praesentium temporibus hic!</p>
  <p>Veritatis eligendi soluta qui voluptate minima ipsa necessitatibus fugit excepturi.</p>
  <p>Sequi, sit ratione enim ullam soluta sed dolores atque harum?</p>
  <p>Pariatur ducimus numquam nam officia corporis necessitatibus adipisci aliquid expedita.</p>
  <p>Delectus maxime sint beatae vitae quos ratione dolorem architecto! Quas!</p>
  <p>Repellat, temporibus tempore quia aperiam quam eaque culpa quasi omnis!</p>
  <p>Dicta nam suscipit, perferendis nemo ipsum ducimus magni quia excepturi.</p>
  <p>Beatae, vitae corporis sapiente ullam voluptatum sint tempora nesciunt aut!</p>
  <p>Ut nemo quia hic esse commodi! Saepe deserunt veritatis commodi.</p>
  <p>Numquam repellendus omnis minus nisi fugit expedita deserunt adipisci odio!</p>
  <p>Nulla ipsa sint tempora deserunt! Illum, est? Temporibus, commodi doloribus?</p>
  <p>Doloribus natus odit magni dolorem voluptatem vero animi tempore esse.</p>
  <p>Sapiente doloremque molestiae itaque soluta quos architecto numquam quo consectetur!</p>
  <p>Rem eius illum fuga consectetur, facere suscipit veniam numquam neque.</p>
  <p>Esse facilis asperiores distinctio eveniet voluptatem nihil beatae corrupti neque!</p>
  <p>Nisi, placeat unde laboriosam nihil culpa vero deserunt minus delectus.</p>
  <p>Placeat, sint vitae nihil debitis eos accusantium facere. Iusto, numquam.</p>
  <p>Rem, quod blanditiis. Expedita pariatur, nam libero a laborum assumenda!</p>
  <p>Provident ipsum voluptates quae rerum aut blanditiis repellendus neque quibusdam?</p>
  <p>Facilis laborum ducimus fuga blanditiis voluptate eveniet? Odio, porro exercitationem?</p>
  <p>Commodi, aliquid fugiat eaque dolores atque tempore autem consequuntur veritatis.</p>
  <p>Repellendus perferendis aut fugiat accusantium rerum dignissimos porro deleniti qui.</p>
  <p>Asperiores ipsam quod doloribus porro? Distinctio, modi. Quia, aspernatur dolore.</p>
  <p>Accusamus iste consectetur quae odio, qui et corporis eveniet? Laudantium!</p>
  <p>Modi facilis voluptatem provident magni ducimus, voluptatibus aliquid ipsa repellendus!</p>
  <p>Explicabo adipisci rerum necessitatibus, maxime aliquam hic obcaecati delectus ab?</p>
  <p>Culpa doloribus perferendis provident nesciunt quisquam maxime et vero ipsa.</p>
  <p>Nisi reprehenderit expedita dolorem at culpa eligendi delectus placeat pariatur?</p>
  <p>Saepe rem delectus minima ratione obcaecati ad nobis praesentium ipsum!</p>
  <p>Facere numquam veritatis debitis in ratione unde porro nam ad.</p>
  <p>Quod omnis illo quia delectus mollitia quos repellendus nisi sit?</p>
  <p>Voluptate doloremque numquam, perspiciatis magnam non consequuntur corporis beatae quia.</p>
  <p>Quia minus dolore voluptates incidunt, molestiae repudiandae nihil aspernatur culpa.</p>
  <p>Facilis distinctio sequi voluptas quia unde tenetur perspiciatis neque harum!</p>
  <p>Amet esse odit repellendus, corporis harum at culpa quam itaque.</p>
  <p>Ipsum temporibus nesciunt esse cumque eaque, saepe provident! Odit, architecto!</p>
  <p>Sed impedit nobis dolores corporis repellendus omnis expedita nisi laboriosam.</p>
  <p>Alias, omnis. Nihil repudiandae ullam quo pariatur, fugiat expedita officia!</p>
  <p>Quo magni accusantium sunt ad quia ullam fugit pariatur atque.</p>
  <p>A ducimus amet reiciendis ex iusto blanditiis omnis neque temporibus!</p>
  <p>Voluptatum asperiores facere magnam nobis quaerat consectetur natus quo magni.</p>
  <p>Quia architecto saepe repellat nulla, debitis nesciunt harum quidem tenetur?</p>
  <p>Itaque animi eos ipsum, optio vitae blanditiis quos alias omnis!</p>
  <p>Natus consequuntur aliquam culpa aliquid provident quae, ducimus excepturi dicta!</p>
  <p>Assumenda ipsam asperiores numquam mollitia culpa similique suscipit ullam eaque.</p>
  <p>Alias quo, nulla tempore obcaecati quis ea distinctio porro et?</p>
  <p>Aspernatur, amet tempora? Vitae fuga delectus repudiandae possimus error veritatis!</p>
  <p>Perferendis inventore expedita et aliquid magni corrupti enim optio sit?</p>
  <p>Delectus, veniam! Laudantium nam harum unde maxime, deleniti est dolores.</p>
  <p>Accusantium saepe eligendi maxime provident officiis. Corporis perspiciatis cum officia.</p>
  <p>Magnam, sed ratione itaque odit eos non beatae nam dolorem?</p>
  <p>Commodi perferendis cupiditate facilis obcaecati distinctio itaque sunt. Dicta, architecto?</p>
  <p>Delectus asperiores laborum accusamus minima! Placeat, quaerat! Adipisci, repudiandae voluptatum?</p>
  <p>Asperiores adipisci iste deserunt molestias magnam. Eligendi maxime optio necessitatibus!</p>
</x-admin.base>
